CREATE TABLE CARS (
    ID         INT IDENTITY(1,1) PRIMARY KEY,
    BRAND      VARCHAR(30),
    MODEL      VARCHAR(30),
    ID_PERSON  INT,
    OBJVERSION	    INT
);


CREATE TABLE COUNTRIES (
    ID           INTEGER IDENTITY(1,1) PRIMARY KEY,
    DESCRIPTION  VARCHAR(50) NOT NULL,
    OBJVERSION	    INT
);


CREATE TABLE EMAILS (
    ID         INT IDENTITY(1,1) PRIMARY KEY,
    ADDRESS    VARCHAR(100),
    ID_PERSON  INT,
    OBJVERSION	    INT
);


CREATE TABLE PEOPLE (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME      VARCHAR(50),
    LAST_NAME       VARCHAR(50),
    AGE             INT,
    BORN_DATE       DATE,
    BORN_DATE_TIME  DATETIME,
    PHOTO           VARBINARY(MAX),
    IS_MALE         INT NOT NULL,
    OBJVERSION	    INT
);


CREATE TABLE PEOPLE_COUNTRIES (
    ID          INTEGER IDENTITY(1,1) PRIMARY KEY,
    ID_PEOPLE   INTEGER NOT NULL,
    ID_COUNTRY  INTEGER NOT NULL,
    OBJVERSION	    INT
);


CREATE TABLE PHONES (
    ID         INT IDENTITY(1,1) PRIMARY KEY,
    NUMBER     VARCHAR(50),
    MODEL      VARCHAR(50),
    ID_PERSON  INT,
    OBJVERSION	    INT
);


CREATE TABLE TODOS (
    ID           INTEGER IDENTITY(1,1) PRIMARY KEY,
    DESCRIPTION  VARCHAR(200) NOT NULL,
    DUE_DATE     DATE NOT NULL,
    DUE_TIME     TIME NOT NULL,
    DONE         INT NOT NULL,
    OBJVERSION   INTEGER NOT NULL
);
